import React from 'react';
import { Printer, ChevronLeft, Download } from 'lucide-react';
import QuestionCard from './QuestionCard';

const QuizDisplay = ({ questions, onBack }) => {
    const [expandAll, setExpandAll] = React.useState(false);

    const handlePrint = () => {
        window.print();
    };

    const toggleExpandAll = () => {
        setExpandAll(!expandAll);
    };

    return (
        <div className="max-w-4xl mx-auto space-y-6">
            {/* Header / Actions */}
            <div className="flex flex-col sm:flex-row items-center justify-between gap-4 print:hidden">
                <button
                    onClick={onBack}
                    className="flex items-center gap-2 text-slate-500 hover:text-slate-800 transition-colors font-medium self-start sm:self-auto"
                >
                    <ChevronLeft className="w-5 h-5" />
                    Back to Configuration
                </button>

                <div className="flex items-center gap-3 self-end sm:self-auto">
                    <button
                        onClick={toggleExpandAll}
                        className="text-sm font-semibold text-blue-600 hover:bg-blue-50 px-3 py-2 rounded-lg transition-colors"
                    >
                        {expandAll ? "Collapse All" : "Expand All Keys"}
                    </button>

                    <button
                        onClick={handlePrint}
                        className="flex items-center gap-2 px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg transition-colors font-semibold"
                    >
                        <Printer className="w-4 h-4" />
                        Print Worksheet
                    </button>
                </div>
            </div>

            {/* Title (for Print) */}
            <div className="hidden print:block text-center mb-8">
                <h1 className="text-3xl font-bold text-slate-900">MathGenie Worksheet</h1>
                <p className="text-slate-500">Generated by AI • {new Date().toLocaleDateString()}</p>
            </div>

            {/* Questions List */}
            <div className="space-y-6 print:space-y-12">
                {questions.map((q, index) => (
                    <QuestionCard
                        key={q.id || index}
                        question={q}
                        index={index}
                        forceOpen={expandAll}
                    />
                ))}
            </div>

            {/* Footer (Print) */}
            <div className="hidden print:block mt-12 pt-8 border-t border-slate-300 text-center text-slate-400 text-sm">
                MathGenie AI Generator
            </div>
        </div>
    );
};

export default QuizDisplay;
